version: '3.7'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - 5435:5432
  prepare:
    build:
      context: .
      target: local-web
    command:
      - sh
      - -c
      - |
        until psql -h "db" -U "postgres" -c '\q'; do >&2 echo "Postgres is unavailable"; sleep 1; done
        test -f .prepared && echo -e "======================================================================\nSkipping prepare script because .prepared file exists.\nDelete the file and try again if you want to re-prepare the DB.\n======================================================================" && exit 0
        sleep 3
        python3 manage.py dbshell <<EOF
        CREATE EXTENSION IF NOT EXISTS citext;
        EOF
        python3 manage.py migrate
        python3 manage.py shell <<EOF
        from django.contrib.auth.models import User
        User.objects.create_superuser('\''beret'\'', '\''beret@hipisi.org.pl'\'', '\''6649beret'\'')"
        EOF
        touch .prepared
    env_file: docker-compose.env
    volumes:
      - .:/main
    depends_on:
      - db
  webpack:
    build:
      context: .
      target: webpack-builder
    command:
      - npm
      - run
      - watch
    volumes:
      - ./src:/js/src
      - dist:/js/dist
    ports:
      - "9000:9000"
  snapburg:
    build:
      context: .
      target: local-web
    env_file: docker-compose.env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      - db
      - prepare
    command: python3 manage.py runserver 0.0.0.0:8008
    volumes:
      - .:/main
      - ./static:/static
      - ./media:/media
      - dist:/main/dist
    ports:
      - "8008:8008"
volumes:
  dbdata:
  storage:
  staticroot:
  dist:
